version: "3.9"
services:
  db:
    image: postgres:15
    env_file: .env.local
    volumes: [pg_data:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env.local
    volumes: [.:/app]               # live-reload
    depends_on: [db]
    ports: ["8000:8000"]

  frontend:
    image: node:20-alpine
    working_dir: /fe
    command: ["sh", "-c", "pnpm install && pnpm dev --host 0.0.0.0"]
    volumes: ["./frontend:/fe"]
    ports: ["5173:5173"]

volumes:
  pg_data: