FROM python:3.12-alpine
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN apk add --no-cache gcc musl-dev libffi-dev
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false \
 && poetry install --no-dev --no-root
COPY . .
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]