# Generated by Django 5.2.4 on 2025-07-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='moderation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'Очікує модерації'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20),
        ),
    ]
