# Generated by Django 5.2.4 on 2025-07-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='promoted_type',
            field=models.CharField(blank=True, choices=[('top', 'Топ оголошення'), ('highlight', 'Виділене'), ('vip', 'VIP')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='promoted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
