# Generated by Django 5.2.4 on 2025-07-28 15:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listing_is_promoted_listing_promoted_type_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listing.brand'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='listing.brand')),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listing.carmodel'),
        ),
        migrations.CreateModel(
            name='ListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Description')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('mileage', models.PositiveIntegerField(help_text='in kilometers', verbose_name='Mileage')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD')], max_length=3, verbose_name='Currency')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='listing.brand', verbose_name='Brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='listing.carmodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Listing Page',
                'verbose_name_plural': 'Listing Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
