# Generated by Django 5.2.4 on 2025-07-19 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('buyer', 'Покупець/Продавець'), ('service', 'СТО'), ('parts', 'Запчастини'), ('rental', 'Прокат'), ('insurance', 'Страхування'), ('dealer', 'Автосалон'), ('admin', 'Адміністратор')], default='buyer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
